import { jsPDF } from "jspdf";
import type { ResultResponse } from "@/types";

export function generatePdf(result: ResultResponse): ArrayBuffer {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  function addText(text: string, fontSize: number, isBold = false, color: [number, number, number] = [30, 30, 30]) {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth) as string[];
    for (const line of lines) {
      if (y > 270) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += fontSize * 0.5;
    }
  }

  function addGap(size = 4) { y += size; }

  // Header
  addText(result.title, 18, true);
  addGap(2);
  addText(`${result.contentType.toUpperCase()} — ${Math.round(result.confidenceScore * 100)}%`, 10, false, [120, 120, 120]);
  addGap(6);

  // Summary
  addText(result.summary, 11);
  addGap(8);

  const output = result.structuredOutput;

  switch (output.contentType) {
    case "recipe": {
      addText("Ingredients", 14, true);
      addGap(2);
      for (const ing of output.ingredients) {
        const parts = [ing.amount, ing.unit, ing.name].filter(Boolean).join(" ");
        addText(`• ${parts}${ing.notes ? ` (${ing.notes})` : ""}`, 10);
      }
      addGap(6);
      addText("Steps", 14, true);
      addGap(2);
      output.steps.forEach((step, i) => { addText(`${i + 1}. ${step}`, 10); addGap(1); });
      break;
    }
    case "business": {
      addText("Key Learnings", 14, true); addGap(2);
      output.keyLearnings.forEach((l) => addText(`• ${l}`, 10));
      addGap(6);
      addText("Action Items", 14, true); addGap(2);
      output.actionItems.forEach((a) => addText(`☐ ${a}`, 10));
      if (output.frameworks.length) { addGap(6); addText("Frameworks", 14, true); addGap(2); output.frameworks.forEach((f) => addText(`• ${f}`, 10)); }
      break;
    }
    case "diy": {
      addText("Materials", 14, true); addGap(2);
      output.materials.forEach((m) => addText(`☐ ${m}`, 10));
      addGap(6);
      addText("Tools", 14, true); addGap(2);
      output.tools.forEach((t) => addText(`• ${t}`, 10));
      addGap(6);
      addText("Steps", 14, true); addGap(2);
      output.steps.forEach((s, i) => { addText(`${i + 1}. ${s}`, 10); addGap(1); });
      break;
    }
    case "workout": {
      addText("Exercises", 14, true); addGap(2);
      output.exercises.forEach((e, i) => {
        const detail = [e.sets && `${e.sets} sets`, e.reps && `${e.reps} reps`, e.duration].filter(Boolean).join(", ");
        addText(`${i + 1}. ${e.name}${detail ? ` — ${detail}` : ""}`, 10);
        if (e.notes) addText(`   ${e.notes}`, 9, false, [100, 100, 100]);
      });
      break;
    }
    default: {
      if ("keyPoints" in output) {
        addText("Key Points", 14, true); addGap(2);
        output.keyPoints.forEach((p) => addText(`• ${p}`, 10));
      }
      if ("suggestedActions" in output) {
        addGap(6); addText("Suggested Actions", 14, true); addGap(2);
        output.suggestedActions.forEach((a) => addText(`☐ ${a}`, 10));
      }
    }
  }

  // Warnings
  if (result.warnings.length) {
    addGap(8);
    addText("⚠ Warnings", 12, true, [180, 120, 0]);
    addGap(2);
    result.warnings.forEach((w) => addText(`• ${w}`, 9, false, [150, 100, 0]));
  }

  // Footer
  y = 285;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Content to Action — AI outputs may contain errors.", margin, y);

  return doc.output("arraybuffer");
}
